### ISSUE TITLE
目录异常

### ISSUE THREAD

**Issue by sgs-site** [sgs-site/Stylish#1]
http://blog.csdn.net/dc_726/article/details/8623879

**Comment by sgs-site** [comment]
这种没有目录，又有版权的。http://blog.csdn.net/jazywoo123/article/details/51094028

**Comment by sgs-site** [comment]
错位
http://blog.csdn.net/jcx5083761/article/details/11764861

**Comment by sgs-site** [comment]
- 优化 去除目录的样式并增大其字体大小 <2017-03-16 Thu 09:11:28>

**Comment by SunDawning** [comment]
表格宽度自动及文字换行

```css
table { width: auto !important; word-break: break-all; }
td { width: auto; }
```
